/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */

import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {},
});
